---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkinsci/blueocean
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true 
        volumeMounts:
        - mountPath: /data 
          name: hostpath-privileged
      volumes:
      - name: hostpath-privileged
      persistentVolumeClaim:
        claimName: jenkins-pvc-volume   
      
       
        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins
