apiVersion: v1

kind: Pod
metadata:
  name: testpod
  labels:
    tier: frontend
spec:
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
