---
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  labels:
    tier: frontend
    app: myapp2
spec:
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  labels:
    tier: frontend
    app: myapp1
spec:
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
