apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    app: myapp
   
  template:
    metadata:
      name: somename
      labels:
        app: myapp
        
    spec:
      containers:
       - name: hello
         image: busybox
         command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
